FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /user-reward ./cmd/app

FROM alpine:latest
WORKDIR /app
COPY --from=builder /user-reward .
COPY .env .

EXPOSE 4000
CMD ["./user-reward"]

# FROM golang:1.21-alpine AS builder

# WORKDIR /app
# COPY . .
# RUN go mod download
# RUN CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/server

# FROM alpine:latest
# RUN apk --no-cache add ca-certificates
# WORKDIR /root/
# COPY --from=builder /app/server .
# COPY --from=builder /app/migrations ./migrations

# EXPOSE 8080
# CMD ["./server"]