FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /user-reward ./cmd/app

FROM alpine:latest
WORKDIR /app
COPY --from=builder /user-reward .
COPY .env .

EXPOSE 4000
CMD ["./user-reward"]
